plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vaonis.vesperahelper'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vaonis.vesperahelper'
        minSdk 29
        targetSdk 35
        versionCode 66
        versionName '0.6.19'
    }
}

dependencies {
    implementation 'commons-net:commons-net:3.11.1'
}
